version: '3.5'
services:
  database:
    image: mariadb
    volumes:
      - ./docker-mariadb-volume:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
  server:
    image: "openjdk:11"
    volumes:
      - ./app/build/libs/backend-all.jar:/app/backend.jar
    command: "java -jar /app/backend.jar"
    ports:
      - 8080:8080
    depends_on:
      database:
        condition: service_started
    environment:
      MYSQL_HOSTNAME: database
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
