version: '3.5'
services:
  database:
    image: mariadb
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
  server:
    image: "openjdk:11"
    volumes:
      - ./app/build/libs/backend.jar:/app/backend.jar
    command: "java -jar /app/backend.jar"
    ports:
      - 8080:8080
    environment:
      MYSQL_HOSTNAME: database
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
